[plugin]
name = "kiloco-portable"
repository = "https://github.com/zeronesun/kilo-portable"
homepage = "https://github.com/zeronesun/kilo-portable"
description = "Kiloco portable version, out of the box"

[versions]
latest = "https://api.github.com/repos/zeronesun/kilo-portable/releases/latest"

[install]
script = """
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
case $(uname -m) in
  x86_64|amd64) ARCH="x64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *) echo "Unsupported arch"; exit 1 ;;
esac

if ldd /bin/ls | grep -q musl; then
  LIBC="musl"
else
  LIBC="glibc"
fi

VER="${version%-portable}"
URL="https://github.com/zeronesun/kilo-portable/releases/download/${version}/kiloco-${VER}-portable-linux-${LIBC}-${ARCH}.tar.gz"

curl -fL "$URL" | tar xz
mkdir -p "${mise_path}/bin"
mv kiloco/bin/* "${mise_path}/bin/"
chmod +x "${mise_path}/bin/kiloco"
echo "Install success!"
"""
