name: Auto Build & Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.TAG }}
    steps:
      - name: Get latest official version
        id: get-tag
        run: |
          # 正确仓库：kilocode，正确latest接口
          TAG=$(curl -s --retry 3 https://api.github.com/repos/Kilo-Org/kilocode/releases/latest | jq -r '.tag_name')
          if [[ "$TAG" == "null" || -z "$TAG" ]]; then
            echo "❌ No version found"
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "✅ Latest version: $TAG"

  build:
    needs: get-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x64
            type: normal
          - os: linux
            arch: x64
            type: musl
          - os: linux
            arch: arm64
            type: normal
          - os: linux
            arch: arm64
            type: musl
          - os: windows
            arch: x64
            type: modern

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y wget jq unzip
      - name: Build portable
        run: |
          chmod +x build/build.sh
          ./build/build.sh ${{ needs.get-version.outputs.tag }} ${{ matrix.arch }} ${{ matrix.type }}
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/*.tar.gz

  release:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: download-artifact@v4
        with:
          name: artifacts
          path: dist
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.get-version.outputs.tag }}-portable
          name: Kilocode ${{ needs.get-version.outputs.tag }} Portable
          files: dist/*.tar.gz
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
